# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 05:51
from __future__ import unicode_literals

import GuavaApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAdopcion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aportacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area_Verde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('enAdopcion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=GuavaApp.models.get_upload_path)),
                ('fechaPublicacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('areaPertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Area_Verde')),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peticion', models.IntegerField()),
                ('comentario', models.CharField(max_length=50)),
                ('abierta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='/media/583_experience_rollover.png', upload_to='Usuarios')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='peticion',
            name='hechaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='peticion',
            name='paraArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Area_Verde'),
        ),
        migrations.AddField(
            model_name='foto',
            name='subidaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='area_verde',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='area_verde',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='aportacion',
            name='hechaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='aportacion',
            name='paraArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Area_Verde'),
        ),
        migrations.AddField(
            model_name='aportacion',
            name='respondiendoPeticion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Peticion'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='hechaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Usuario'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='paraArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuavaApp.Area_Verde'),
        ),
    ]
