# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuavaApp', '0002_auto_20171121_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='/Usuarios/2.jpg', upload_to='Usuarios'),
        ),
    ]
