# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuavaApp', '0004_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='arboles',
            field=models.IntegerField(default=0),
        ),
    ]
