# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuavaApp', '0006_auto_20171122_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_verde',
            name='enAdopcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
