# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuavaApp', '0007_auto_20171122_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
